Fix BSD build error
Return an empty string instead of NULL from csv_escape() to silence
build error:

inotifywait.c: In function 'output_event_csv':
inotifywait.c:144:2: error: '%s' directive argument is null [-Werror=format-overflow=]
  144 |  printf("%s,", csv_escape(inotifytools_event_to_str(event->mask)));